[package]
name = "nettish"
version = "0.1.0"
edition = "2024"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
repository = "https://github.com/Ralith/nettish"
readme = "README.md"

[dependencies]
